### PR TITLE
Fix: Highlighting searched term should ignore accents

### LINKED ISSUE #2312: (Bug report) Highlighting searched term should ignore accents
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.5

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Pop!_OS 20.04

### Expected Behavior

Follow-up issue for https://github.com/zadam/trilium/issues/2182.

When you search for "Zürich" and page named "Zurich" comes up, the "Zurich" part should be highlighted. It looks like the highlighting does not take the accent normalization into account.

### Actual Behavior

image

Note that when searching for "zurich", pages with "Zürich" do not have the word highlighted.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Myzel394**
closes #2312

### CODE REVIEW

File: src/services/search/services/search.js [hunk 1]
```diff
@@ -83,12 +84,8 @@ function findResultsWithExpression(expression, searchContext) {
                 throw new Error(`Can't find note path for note ${JSON.stringify(note.getPojo())}`);
             }
 
-            if (notePathArray.includes("hidden")) {
```
Comment (zadam) [inline src/services/search/services/search.js:86]: Please rebase, this shouldn't be removed.

**Comment by Myzel394** [comment]
merged

**Review by zadam — APPROVED** [review]
